"""Unified error codes for laser-beam-qa."""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    E_DEVICE_RAYCI_NOT_RUNNING = "E_DEVICE_RAYCI_NOT_RUNNING"
    E_DEVICE_RAYCI_CONNECT_FAILED = "E_DEVICE_RAYCI_CONNECT_FAILED"
    E_DEVICE_CAMERA_TIMEOUT = "E_DEVICE_CAMERA_TIMEOUT"
    E_DEVICE_STAGE_CONNECT_FAILED = "E_DEVICE_STAGE_CONNECT_FAILED"
    E_DEVICE_STAGE_NOT_HOMED = "E_DEVICE_STAGE_NOT_HOMED"
    E_DEVICE_STAGE_MOVE_TIMEOUT = "E_DEVICE_STAGE_MOVE_TIMEOUT"
    E_DEVICE_STAGE_SOFT_LIMIT = "E_DEVICE_STAGE_SOFT_LIMIT"
    E_SAFETY_INTERLOCK_OPEN = "E_SAFETY_INTERLOCK_OPEN"
    E_SAFETY_COLLISION_RISK = "E_SAFETY_COLLISION_RISK"
    E_IMAGE_SATURATED = "E_IMAGE_SATURATED"
    E_IMAGE_LOW_SIGNAL = "E_IMAGE_LOW_SIGNAL"
    E_IMAGE_EDGE_CLIPPED = "E_IMAGE_EDGE_CLIPPED"
    E_IMAGE_ROI_NOT_FOUND = "E_IMAGE_ROI_NOT_FOUND"
    E_ANALYSIS_D4SIGMA_FAILED = "E_ANALYSIS_D4SIGMA_FAILED"
    E_ANALYSIS_ZSCAN_TOO_FEW_POINTS = "E_ANALYSIS_ZSCAN_TOO_FEW_POINTS"
    E_ANALYSIS_ZSCAN_FIT_FAILED = "E_ANALYSIS_ZSCAN_FIT_FAILED"
    E_REPORT_GENERATION_FAILED = "E_REPORT_GENERATION_FAILED"
    E_USER_ABORT = "E_USER_ABORT"


ERROR_CODE_VALUES = frozenset(code.value for code in ErrorCode)

E_DEVICE_RAYCI_NOT_RUNNING = ErrorCode.E_DEVICE_RAYCI_NOT_RUNNING.value
E_DEVICE_RAYCI_CONNECT_FAILED = ErrorCode.E_DEVICE_RAYCI_CONNECT_FAILED.value
E_DEVICE_CAMERA_TIMEOUT = ErrorCode.E_DEVICE_CAMERA_TIMEOUT.value
E_DEVICE_STAGE_CONNECT_FAILED = ErrorCode.E_DEVICE_STAGE_CONNECT_FAILED.value
E_DEVICE_STAGE_NOT_HOMED = ErrorCode.E_DEVICE_STAGE_NOT_HOMED.value
E_DEVICE_STAGE_MOVE_TIMEOUT = ErrorCode.E_DEVICE_STAGE_MOVE_TIMEOUT.value
E_DEVICE_STAGE_SOFT_LIMIT = ErrorCode.E_DEVICE_STAGE_SOFT_LIMIT.value
E_SAFETY_INTERLOCK_OPEN = ErrorCode.E_SAFETY_INTERLOCK_OPEN.value
E_SAFETY_COLLISION_RISK = ErrorCode.E_SAFETY_COLLISION_RISK.value
E_IMAGE_SATURATED = ErrorCode.E_IMAGE_SATURATED.value
E_IMAGE_LOW_SIGNAL = ErrorCode.E_IMAGE_LOW_SIGNAL.value
E_IMAGE_EDGE_CLIPPED = ErrorCode.E_IMAGE_EDGE_CLIPPED.value
E_IMAGE_ROI_NOT_FOUND = ErrorCode.E_IMAGE_ROI_NOT_FOUND.value
E_ANALYSIS_D4SIGMA_FAILED = ErrorCode.E_ANALYSIS_D4SIGMA_FAILED.value
E_ANALYSIS_ZSCAN_TOO_FEW_POINTS = ErrorCode.E_ANALYSIS_ZSCAN_TOO_FEW_POINTS.value
E_ANALYSIS_ZSCAN_FIT_FAILED = ErrorCode.E_ANALYSIS_ZSCAN_FIT_FAILED.value
E_REPORT_GENERATION_FAILED = ErrorCode.E_REPORT_GENERATION_FAILED.value
E_USER_ABORT = ErrorCode.E_USER_ABORT.value


class LBQAError(RuntimeError):
    """Project exception carrying a stable error code."""

    def __init__(self, error_code: ErrorCode | str, message: str) -> None:
        self.error_code = str(error_code)
        super().__init__(f"{self.error_code}: {message}")
